# This is a basic workflow to help you get started with Actions

name: snyk-test-pr

# the jobs in this workflow only runs when a tag is pushed to this repo
on:
  pull_request:
    branches:
    - main
    paths:
      - "*Pipfile"
      - "*requirements.txt"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  snyk-monitor:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Install Snyk
        run: npm install snyk snyk-delta > /dev/null 2>&1

      - name: Setup Pip
        run: pip install -r requirements.txt
      
      - name: Snyk Test & Filter
        env: 
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk test --file=requirements.txt --package-manager=pip | snyk-delta